name: CI

on: [push, pull_request]

jobs:
  test:
    name: Run tests
    runs_on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        php: ["7.2", "7.3"]
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php}}
          tools: phpize
      - run: phpize
      - run: ./configure
      - run: make
      - REPORT_EXIT_STATUS=1 NO_INTERACTION=1 TEST_PHP_ARGS="--show-diff" make test
